"""
Hooks module for Claude Code.

Provides hook registry, event types, and lifecycle management for user hooks,
plugin hooks, and internal callback hooks.
"""

from .registry import (
    HookEventHandler,
    HookEventMetadata,
    HookExecutionEvent,
    HookExecutionEventType,
    HookProgressEvent,
    HookRegistry,
    HookResponseEvent,
    HookStartedEvent,
    MatcherMetadata,
    PendingAsyncHook,
    get_hook_event_metadata,
    get_hook_registry,
    get_matcher_metadata,
)
from .types import (
    HOOK_EVENTS,
    AgentHook,
    AggregatedHookResult,
    AsyncHookJSONOutput,
    BashCommandHook,
    ElicitationHookInput,
    ElicitationResultHookInput,
    FileChangedHookInput,
    HookBlockingError,
    HookCallback,
    HookCallbackContext,
    HookCallbackMatcher,
    HookCommand,
    HookEvent,
    HookInput,
    HookJSONOutput,
    HookMatcher,
    HookProgress,
    HookResult,
    HooksSettings,
    HttpHook,
    InstructionsLoadedHookInput,
    NotificationHookInput,
    PermissionBehavior,
    PermissionDeniedHookInput,
    PermissionMode,
    PermissionRequestAllowResult,
    PermissionRequestDenyResult,
    PermissionRequestHookInput,
    PermissionRequestResult,
    PostCompactHookInput,
    PostToolUseFailureHookInput,
    PostToolUseHookInput,
    PreCompactHookInput,
    PreToolUseHookInput,
    PromptHook,
    PromptRequest,
    PromptRequestOption,
    PromptResponse,
    SessionEndHookInput,
    SessionStartHookInput,
    SetupHookInput,
    StopFailureHookInput,
    StopHookInput,
    SubagentStartHookInput,
    SubagentStopHookInput,
    SyncHookJSONOutput,
    TaskCompletedHookInput,
    TaskCreatedHookInput,
    TeammateIdleHookInput,
    UserPromptSubmitHookInput,
    WorktreeCreateHookInput,
    WorktreeRemoveHookInput,
    is_async_hook_output,
    is_hook_event,
    is_sync_hook_output,
)

__all__ = [
    # Registry (from registry.py)
    "HookEventHandler",
    "HookEventMetadata",
    "HookExecutionEvent",
    "HookExecutionEventType",
    "HookProgressEvent",
    "HookRegistry",
    "HookResponseEvent",
    "HookStartedEvent",
    "MatcherMetadata",
    "PendingAsyncHook",
    "get_hook_event_metadata",
    "get_hook_registry",
    "get_matcher_metadata",
    # Hook input types (from types.py)
    "ElicitationHookInput",
    "ElicitationResultHookInput",
    "FileChangedHookInput",
    "HookCallback",
    "HookCallbackContext",
    "HookCallbackMatcher",
    "InstructionsLoadedHookInput",
    "NotificationHookInput",
    "PermissionDeniedHookInput",
    "PermissionRequestHookInput",
    "PostCompactHookInput",
    "PostToolUseFailureHookInput",
    "PostToolUseHookInput",
    "PreCompactHookInput",
    "PreToolUseHookInput",
    "SessionEndHookInput",
    "SessionStartHookInput",
    "SetupHookInput",
    "StopFailureHookInput",
    "StopHookInput",
    "SubagentStartHookInput",
    "SubagentStopHookInput",
    "TaskCompletedHookInput",
    "TaskCreatedHookInput",
    "TeammateIdleHookInput",
    "UserPromptSubmitHookInput",
    "WorktreeCreateHookInput",
    "WorktreeRemoveHookInput",
    # Hook output types (from types.py)
    "AggregatedHookResult",
    "AsyncHookJSONOutput",
    "HookBlockingError",
    "HookJSONOutput",
    "HookProgress",
    "HookResult",
    "PermissionRequestAllowResult",
    "PermissionRequestDenyResult",
    "PermissionRequestResult",
    "SyncHookJSONOutput",
    # Hook command types (from types.py)
    "AgentHook",
    "BashCommandHook",
    "HookCommand",
    "HookMatcher",
    "HooksSettings",
    "HttpHook",
    "PromptHook",
    # Hook event constants and utilities (from types.py)
    "HOOK_EVENTS",
    "HookEvent",
    "HookInput",
    "is_async_hook_output",
    "is_hook_event",
    "is_sync_hook_output",
    # Permission types (from types.py)
    "PermissionBehavior",
    "PermissionMode",
    # Elicitation types (from types.py)
    "PromptRequest",
    "PromptRequestOption",
    "PromptResponse",
]
