#!/usr/bin/env python3
"""Bootstrap the mozi project skeleton."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap mozi project skeleton")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    parser.add_argument(
        "--manifest",
        default="docs/init/tasks/phase_0.json",
        help="Path to phase_0.json manifest",
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"ERROR: Manifest not found: {manifest_path}")
        return 1

    # Read manifest
    with open(manifest_path) as f:
        manifest = json.load(f)

    # Process all children recursively
    created, skipped, errors = process_manifest(manifest, args.force)

    print(f"\nDone: {len(created)} created, {len(skipped)} skipped, {len(errors)} errors")
    return 1 if errors else 0


def process_manifest(manifest: dict, force: bool) -> tuple[list[str], list[str], list[str]]:
    """Process all tasks from manifest."""
    created: list[str] = []
    skipped: list[str] = []
    errors: list[str] = []

    for iteration in manifest.get("iterations", []):
        for task in iteration.get("tasks", []):
            for child in task.get("children", []):
                file_path = child.get("file")
                if not file_path:
                    continue

                path = Path(file_path)
                try:
                    if path.exists() and not force:
                        skipped.append(str(path))
                        continue

                    # Determine what to create based on file path
                    if create_from_template(path):
                        created.append(str(path))
                except Exception as e:
                    errors.append(f"{path}: {e}")

    return created, skipped, errors


def create_from_template(path: Path) -> bool:
    """Create file from embedded template based on file path.

    Returns True if created, False if skipped.
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    # Check specific paths first before general suffix checks
    if str(path).startswith(".claude/rules/"):
        # Rules from manifest - create minimal stub
        rule_name = path.stem.replace("-", "_")
        path.write_text(f"# {rule_name.replace('_', ' ').title()}\n\n")
        return True
    elif str(path).startswith("docs/foundation/"):
        # Docs directories - create as placeholders
        path.mkdir(parents=True, exist_ok=True)
        return True
    elif path.suffix == ".lock":
        # uv.lock is generated by 'uv lock', skip
        return False
    elif path.name == "__init__.py":
        path.write_text("")
        return True
    elif path.suffix == ".md":
        path.write_text(f"# {path.stem.replace('_', ' ').title()}\n\n")
        return True
    elif path.name == "pyproject.toml":
        path.write_text(TEMPLATES["pyproject.toml"])
        return True
    elif path.name == "ruff.toml":
        path.write_text(TEMPLATES["ruff.toml"])
        return True
    elif path.name == "mypy.ini":
        path.write_text(TEMPLATES["mypy.ini"])
        return True
    elif path.name == "pytest.ini":
        path.write_text(TEMPLATES["pytest.ini"])
        return True
    elif path.name == "bandit.toml":
        path.write_text(TEMPLATES["bandit.toml"])
        return True
    elif path.name == ".gitignore":
        path.write_text(TEMPLATES[".gitignore"])
        return True
    elif path.name == ".pre-commit-config.yaml":
        path.write_text(TEMPLATES[".pre-commit-config.yaml"])
        return True
    elif path.name == "__version__.py":
        path.write_text(TEMPLATES["__version__.py"])
        return True
    elif path.name == "exceptions.py":
        path.write_text(TEMPLATES["exceptions.py"])
        return True
    else:
        path.write_text("")
        return True


TEMPLATES: dict[str, str] = {
    "__version__.py": '''\
"""Version info."""

__version__ = "0.1.0"
__version_info__ = tuple(int(x) for x in __version__.split("."))
''',
    "exceptions.py": '''\
"""Mozi exceptions."""


class MoziError(Exception):
    """Base exception for mozi."""

    pass


class ConfigurationError(MoziError):
    """Configuration related errors."""

    pass


class ExecutionError(MoziError):
    """Execution related errors."""

    pass
''',
    "pyproject.toml": """\
[project]
name = "mozi"
version = "0.1.0"
description = "Mozi AI Coding Agent"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.27.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.4.0",
    "mypy>=1.10.0",
    "pytest>=8.0.0",
    "pytest-cov>=5.0.0",
    "bandit>=1.7.0",
    "pre-commit>=3.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
quote-style = "double"

[tool.ruff.isort]
known-first-party = ["mozi"]

[tool.mypy]
python_version = "3.11"
strict = true

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "e2e: End-to-end tests",
    "slow: Slow running tests",
]
""",
    "ruff.toml": """\
line-length = 100
quote-style = "double"

[isort]
known-first-party = ["mozi"]
""",
    "mypy.ini": """\
[mypy]
python_version = 3.11
strict = true
""",
    "pytest.ini": """\
[pytest]
testpaths = tests
markers =
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests
    slow: Slow running tests
""",
    "bandit.toml": """\
[bandit]
targets = ["mozi/"]
confidence_level = 1
severity_level = 1
""",
    ".gitignore": """\
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
dist/
build/
*.egg-info/

# Virtual environments
.venv/

# Test coverage
.coverage
htmlcov/

# IDE
.vscode/
.idea/

# OS
.DS_Store
""",
    ".pre-commit-config.yaml": """\
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames = true
""",
}


if __name__ == "__main__":
    sys.exit(main())
