"""Tests for bootstrap_project.py."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from scripts.bootstrap_project import create_from_template, process_manifest


class TestCreateFromTemplate:
    """Tests for create_from_template function."""

    def test_creates_init_py_empty(self, tmp_path: Path) -> None:
        """__init__.py is created as empty file."""
        path = tmp_path / "__init__.py"
        create_from_template(path)
        assert path.exists()
        assert path.read_text() == ""

    def test_creates_md_with_title(self, tmp_path: Path) -> None:
        """Markdown files get title from filename."""
        path = tmp_path / "test_document.md"
        create_from_template(path)
        assert path.exists()
        content = path.read_text()
        assert content.startswith("# Test Document\n\n")

    def test_creates_pyproject_toml(self, tmp_path: Path) -> None:
        """pyproject.toml uses correct template."""
        path = tmp_path / "pyproject.toml"
        create_from_template(path)
        content = path.read_text()
        assert '[project]' in content
        assert 'name = "mozi"' in content

    def test_creates_ruff_toml(self, tmp_path: Path) -> None:
        """ruff.toml uses correct template."""
        path = tmp_path / "ruff.toml"
        create_from_template(path)
        content = path.read_text()
        assert 'line-length = 100' in content
        assert 'quote-style = "double"' in content

    def test_creates_mypy_ini(self, tmp_path: Path) -> None:
        """mypy.ini uses correct template."""
        path = tmp_path / "mypy.ini"
        create_from_template(path)
        content = path.read_text()
        assert '[mypy]' in content
        assert 'strict = true' in content

    def test_creates_pytest_ini(self, tmp_path: Path) -> None:
        """pytest.ini uses correct template."""
        path = tmp_path / "pytest.ini"
        create_from_template(path)
        content = path.read_text()
        assert '[pytest]' in content
        assert 'testpaths = tests' in content

    def test_creates_bandit_toml(self, tmp_path: Path) -> None:
        """bandit.toml uses correct template."""
        path = tmp_path / "bandit.toml"
        create_from_template(path)
        content = path.read_text()
        assert '[bandit]' in content

    def test_creates_gitignore(self, tmp_path: Path) -> None:
        """.gitignore uses correct template."""
        path = tmp_path / ".gitignore"
        create_from_template(path)
        content = path.read_text()
        assert '__pycache__/' in content
        assert '.venv/' in content

    def test_creates_precommit_config(self, tmp_path: Path) -> None:
        """.pre-commit-config.yaml uses correct template."""
        path = tmp_path / ".pre-commit-config.yaml"
        create_from_template(path)
        content = path.read_text()
        assert 'repos:' in content

    def test_creates_version_file(self, tmp_path: Path) -> None:
        """__version__.py uses correct template."""
        path = tmp_path / "__version__.py"
        create_from_template(path)
        content = path.read_text()
        assert '__version__ = "0.1.0"' in content

    def test_creates_exceptions_file(self, tmp_path: Path) -> None:
        """exceptions.py uses correct template."""
        path = tmp_path / "exceptions.py"
        create_from_template(path)
        content = path.read_text()
        assert 'class MoziError(Exception)' in content

    def test_skips_lock_files(self, tmp_path: Path) -> None:
        """.lock files are skipped (generated by uv lock)."""
        path = tmp_path / "uv.lock"
        create_from_template(path)
        # Should not create the file
        assert not path.exists()

    def test_creates_unknown_files_empty(self, tmp_path: Path) -> None:
        """Unknown file types get empty content."""
        path = tmp_path / "unknown.txt"
        create_from_template(path)
        assert path.exists()
        assert path.read_text() == ""


class TestCreateFromTemplateRelative:
    """Tests for create_from_template with relative paths (special case handlers)."""

    def test_creates_rules_stub_with_relative_path(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """.claude/rules/ files get minimal stub when using relative path."""
        # The .claude/rules/ handler checks for relative paths
        monkeypatch.chdir(tmp_path)
        path = Path(".claude/rules/test-rule.md")
        create_from_template(path)
        content = path.read_text()
        # The rule name "test-rule" -> "test_rule" -> "test rule" -> title cased, plus " Rule" suffix
        assert content.startswith("# Test Rule Rule\n\n")

    def test_creates_docs_foundation_as_directory_relative(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """docs/foundation/ paths are created as directories with relative path."""
        monkeypatch.chdir(tmp_path)
        path = Path("docs/foundation/architecture")
        create_from_template(path)
        assert path.is_dir()


class TestProcessManifest:
    """Tests for process_manifest function."""

    def _make_manifest(self, files: list[str]) -> dict[str, Any]:
        """Helper to create a minimal manifest with given files."""
        return {
            "iterations": [
                {
                    "tasks": [
                        {
                            "children": [{"file": f} for f in files]
                        }
                    ]
                }
            ]
        }

    def test_creates_single_file(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """process_manifest creates a single file relative to cwd."""
        monkeypatch.chdir(tmp_path)
        manifest = self._make_manifest(["test.txt"])
        created, skipped, errors = process_manifest(manifest, force=False)
        assert len(created) == 1
        assert Path("test.txt").exists()

    def test_skips_existing_files_by_default(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Existing files are skipped unless force=True."""
        monkeypatch.chdir(tmp_path)
        existing = Path("existing.txt")
        existing.write_text("original")
        manifest = self._make_manifest(["existing.txt"])
        created, skipped, errors = process_manifest(manifest, force=False)
        assert len(created) == 0
        assert len(skipped) == 1
        assert existing.read_text() == "original"

    def test_force_overwrites_existing(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """With force=True, existing files are overwritten."""
        monkeypatch.chdir(tmp_path)
        existing = Path("test.txt")
        existing.write_text("original")
        manifest = self._make_manifest(["test.txt"])
        created, skipped, errors = process_manifest(manifest, force=True)
        assert len(created) == 1
        assert len(skipped) == 0
        # File should be recreated (empty for .txt)
        assert existing.read_text() == ""

    def test_creates_nested_files(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Nested paths are created with parent directories."""
        monkeypatch.chdir(tmp_path)
        manifest = self._make_manifest(["docs/test.md"])
        created, skipped, errors = process_manifest(manifest, force=False)
        assert len(created) == 1
        assert Path("docs/test.md").exists()

    def test_skips_lock_files_in_manifest(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Lock files in manifest are skipped."""
        monkeypatch.chdir(tmp_path)
        manifest = self._make_manifest(["uv.lock"])
        created, skipped, errors = process_manifest(manifest, force=False)
        assert len(created) == 0
        assert len(errors) == 0
        # uv.lock should not be created
        assert not Path("uv.lock").exists()

    def test_returns_empty_on_empty_manifest(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Empty manifest produces empty results."""
        monkeypatch.chdir(tmp_path)
        manifest: dict[str, Any] = {"iterations": []}
        created, skipped, errors = process_manifest(manifest, force=False)
        assert created == []
        assert skipped == []
        assert errors == []

    def test_handles_missing_file_field(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Children without file field are skipped."""
        monkeypatch.chdir(tmp_path)
        manifest = {
            "iterations": [
                {
                    "tasks": [
                        {"children": [{"no_file": "value"}]}
                    ]
                }
            ]
        }
        created, skipped, errors = process_manifest(manifest, force=False)
        assert created == []
        assert errors == []
